"""Type stub for engine.py's Engine: TorchBind classes resolve to Any in
torch's own stubs, so this is what gives it real method signatures. Paired
with engine.py by name; never imported at runtime itself.
"""

from typing import Any

import torch
from torch import Tensor

from pulsar.rt.session import SessionState

class Engine:
    def __init__(
        self,
        weights: dict[str, Tensor],
        config: dict[str, Any],
        dtype: torch.dtype,
    ) -> None: ...
    def create_session(
        self, system_tokens: list[int], overrides: dict[str, Any]
    ) -> int: ...
    def feed(self, seq_id: int, tokens: list[int]) -> None: ...
    def set_decode_budget(self, seq_id: int, budget: int | None = None) -> None: ...
    def step(self, n: int) -> tuple[list[int], list[int], list[bool]]: ...
    def release(self, seq_id: int) -> None: ...
    def session_state(self, seq_id: int) -> SessionState: ...
    def active_tokens_count(self, seq_id: int) -> int: ...
    def demoted_tokens_count(self, seq_id: int) -> int: ...
    def stats(self, seq_id: int) -> dict[str, int | list[int] | list[float]]: ...
    def context_page_ids(self, seq_id: int) -> list[int]: ...
    def context_pages(self, seq_id: int) -> list[list[int]]: ...
    def history_page_ids(self, seq_id: int) -> list[int]: ...
    def history_pages(self, seq_id: int) -> list[list[int]]: ...
